name: Deploy pages

on:
  workflow_dispatch:
  push:
    branches: [ stable-docs ]
    paths: [ 'docs/**', 'CHANGELOG.md' , 'LICENSE.md' ]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Generate pages
        uses: jpikl/hatcher@v0.1

      - name: Deploy pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./pages
          force_orphan: true
